### ISSUE TITLE
Issue issues

### ISSUE THREAD

**Issue by philclifford** [ymauray/quickgui#1]
Excellent to see the new org appear with the emergence of the one-true-gui  :clap:  :clap:  :clap: 
But I see [quickgui/quickgui](https://github.com/quickgui/quickgui) appears to have issues turned off...  (I have no issues, but did notice )

**Comment by ymauray** [comment]
Thanks for the issue about the issues. A fix has been issued and there is no more issue. I mean there are issues, now. But since that was not an issue, I guess we’re good. Right ? Anyway … 🤣

**Comment by ymauray** [comment]
Closing this, because why not.
